### ISSUE TITLE
Adding Google Java Format Action

### ISSUE THREAD

**Issue by iamrajiv** [sijan8s3/MusicPlayer#11]
Google Java Format Action will automatically format your Java files using [Google Java Style guidelines](https://google.github.io/styleguide/javaguide.html).

**Comment by iamrajiv** [comment]
@sijan8s3 I want work on this please assign me and label  Hacktoberfest.

**Comment by sijan8s3** [comment]
@iamrajiv 
you're assigned and the issue you opened has been labeled as hacktoberfest.
Don't forget to star the repository.
Happy Hacktober! :)
