### ISSUE TITLE
Update Readme.md 

### ISSUE THREAD

**Issue by VishnuSanal** [sijan8s3/MusicPlayer#19]
Update Readme.md with more screenshots, better formatting, etc.

PS:Please let me work on this

**Comment by sijan8s3** [comment]
you're welcome to contribute.
Please, star the repo,
fork it,
make the changes,
and then,
send the PR request.

I'd be happy to accept and merge.

**Comment by andrehgdias** [comment]
Hey, there are currently 4 PRs from this issue, may I make an other one? I'll be modfying README.md a little more...

**Comment by sijan8s3** [comment]
@andrehgdias 
yes, there are 4PRs,
none of them are good so i just ignored them,
(cancelling hampers the hacktober's progress).

for you,
if you can add a few more lines, 
I will be happy to merge the PR.
make sure it's bit more than just typos errors.

**Comment by andrehgdias** [comment]
I attached a preview #24
