### ISSUE TITLE
Disable Github Actions

### ISSUE THREAD

**Issue by moinahmed9999** [sijan8s3/MusicPlayer#30]
Disable Github Actions. It is creating useless commits in the name of formatting. The Code is already pretty neat.

**Comment by moinahmed9999** [comment]
For reference : https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository

**Comment by sijan8s3** [comment]
@moinahmed9999 
sure, thank you! :)

**Comment by sijan8s3** [comment]
@moinahmed9999 
i disabled,
check if its correct!
and close the issue!

**Comment by moinahmed9999** [comment]
Yes, it is disabled now.
